import {test} from 'node:test';
import assert from 'node:assert/strict';
import {SCENARIOS,createGame,applyAction,policy,activeAgent,disrupt,agentPacket,knowledge,evidenceFor,scenarioFor,type Game,type Mode} from '../lib/game.ts';
function run(g:Game){for(let i=0;i<110&&g.phase!=='escaped'&&g.phase!=='stalled';i++){const id=activeAgent(g);g=applyAction(g,id,policy(g,id));}return g;}
test('team escapes every mission across 12 puzzle seeds without invalid actions',()=>{for(const scenario of SCENARIOS)for(let seed=1;seed<=12;seed++){const g=run(createGame('team',seed,scenario.id));assert.equal(g.phase,'escaped',`${scenario.id} seed ${seed}`);assert.equal(g.failures,0);assert.equal(g.events.filter(e=>e.type==='message').length,4);assert.equal(g.tokens,0);}});
test('missions provide distinct evidence, codes, and stabilization timing',()=>{const records=SCENARIOS.map(s=>evidenceFor(1,s.id));assert.equal(new Set(records.map(es=>es.find(e=>e.id==='M-01')!.title)).size,3);assert.equal(new Set(records.map(es=>es.find(e=>e.id==='L-02')!.text.match(/\d{4}/)![0])).size,3);assert.deepEqual(SCENARIOS.map(s=>s.stabilizationTicks),[2,3,4]);});
test('each mission enforces its own stabilization interval',()=>{for(const scenario of SCENARIOS){let g=createGame('team',1,scenario.id);g=applyAction(g,'atlas',{type:'operate',target:'cooling'});for(let i=1;i<scenario.stabilizationTicks;i++)g=applyAction(g,'sage',{type:'wait'});g=applyAction(g,'atlas',{type:'operate',target:'power'});assert.equal(g.power,true,scenario.id);assert.equal(g.failures,0,scenario.id);}});
test('scenario identity reaches the local-agent packet',()=>{const g=createGame('team',7,'solar-blackout'),packet=agentPacket(g,'nova');assert.equal(packet.scenario.id,'solar-blackout');assert.equal(packet.station.stabilizationTicks,scenarioFor('solar-blackout').stabilizationTicks);});
test('single controller has pooled observations and can solve identical puzzles',()=>{const g=run(createGame('single'));assert.equal(g.phase,'escaped');assert.equal(g.events.filter(e=>e.type==='message').length,0);assert.equal(knowledge(g,'atlas').length,8);});
test('independent agents stall without leaked cross-room evidence',()=>{const g=run(createGame('independent'));assert.equal(g.phase,'stalled');for(const id of ['nova','cipher','atlas','sage'] as const)assert.equal(g.known[id].length,2);});
test('initial observation packet does not leak clue text or code',()=>{const p=agentPacket(createGame(),'nova');assert.equal(p.evidence.length,0);assert.equal(JSON.stringify(p).includes('4379'),false);assert.equal(p.inspectable.length,2);});
test('cannot inspect another room or share unobserved evidence',()=>{let g=createGame();g=applyAction(g,'nova',{type:'inspect',target:'L-02'});g=applyAction(g,'nova',{type:'share',evidence:['L-02']});assert.equal(g.failures,2);assert.deepEqual(g.known.sage,[]);});
test('power rejects missing or insufficient cooling; door rejects incomplete interlocks',()=>{let g=createGame();g=applyAction(g,'atlas',{type:'operate',target:'power'});assert.equal(g.power,false);g=applyAction(g,'atlas',{type:'operate',target:'cooling'});g=applyAction(g,'atlas',{type:'operate',target:'power'});assert.equal(g.power,false);g=applyAction(g,'sage',{type:'operate',target:'exit'});assert.notEqual(g.phase,'escaped');assert.equal(g.failures,3);});
test('incorrect old code is rejected',()=>{let g=createGame();g=applyAction(g,'atlas',{type:'operate',target:'cooling'});g=applyAction(g,'sage',{type:'wait'});g=applyAction(g,'atlas',{type:'operate',target:'power'});g=applyAction(g,'atlas',{type:'operate',target:'authorize:1904'});assert.equal(g.decoded,false);assert.equal(g.failures,1);});
test('team recovers from faults at several mission stages',()=>{for(const at of [1,8,16,24,29]){let g=createGame();for(let i=0;i<at;i++){const id=activeAgent(g);g=applyAction(g,id,policy(g,id));}if(g.phase==='escaped')continue;g=disrupt(g);assert.equal(g.power,false);assert.equal(g.holds.length,0);g=run(g);assert.equal(g.phase,'escaped',`fault at ${at}`);assert.equal(g.repaired,true);assert.equal(g.failures,0);}});
test('actions are immutable for reliable replay',()=>{const g=createGame();const next=applyAction(g,'nova',{type:'inspect',target:'M-01'});assert.equal(g.tick,0);assert.equal(g.known.nova.length,0);assert.equal(next.known.nova.length,1);});
test('terminal state cannot be changed by additional actions',()=>{const g=run(createGame());assert.deepEqual(applyAction(g,'atlas',{type:'operate',target:'cooling'}),g);});
