'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import dynamic from 'next/dynamic';
import {Play,Pause,RotateCcw,ArrowUpRight,ChevronRight,Radio,ScanLine,Layers,Network,Zap,LockKeyhole,DoorOpen,Check,Settings2,Info,Maximize,SkipForward,Download,FlaskConical,Unplug,Orbit,TriangleAlert,Volume2,VolumeX,ArrowRight,LoaderCircle} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Slider} from '@/components/ui/slider';
import {AGENTS,createGame,policy,applyAction,activeAgent,disrupt,evidenceFor,knowledge,agentPacket,type Game,type AgentId,type Mode,type Action} from '@/lib/game';
const Station=dynamic(()=>import('@/components/game/Station'),{ssr:false,loading:()=> <div className="loading-station"><Orbit size={30}/><span>ASSEMBLING STATION</span></div>});
const modes={team:'Coordinated team',single:'Single controller',independent:'Independent agents'};
const pad=(n:number)=>String(n).padStart(2,'0');
export default function Page(){
 const [game,setGame]=useState<Game>(()=>createGame()),[running,setRunning]=useState(false),[speed,setSpeed]=useState(1),[selected,setSelected]=useState<AgentId|null>(null),[tab,setTab]=useState('comms'),[modal,setModal]=useState<'about'|'settings'|'compare'|null>(null),[backend,setBackend]=useState('simulation'),[model,setModel]=useState(''),[models,setModels]=useState<string[]>([]),[error,setError]=useState(''),[checking,setChecking]=useState(false),[busy,setBusy]=useState(false),[links,setLinks]=useState(true),[resetView,setResetView]=useState(0),[sound,setSound]=useState(false),[history,setHistory]=useState<Game[]>([]),[replay,setReplay]=useState<number|null>(null),[focusEvidence,setFocusEvidence]=useState<string|null>(null),[results,setResults]=useState<Game[]>([]),[preferencesReady,setPreferencesReady]=useState(false);
 const state=useRef(game),inflight=useRef(false),generation=useRef(0),abort=useRef<AbortController|null>(null),log=useRef<HTMLDivElement>(null),audio=useRef<AudioContext|null>(null);state.current=game;
 const view=replay===null?game:history[replay]||game;
 const setMission=(g:Game)=>{state.current=g;setGame(g);setHistory(h=>[...h,g]);};
 const beep=useCallback(()=>{if(!sound)return;try{const a=audio.current||(audio.current=new AudioContext());a.resume();const o=a.createOscillator(),gain=a.createGain();o.frequency.value=640;gain.gain.setValueAtTime(.025,a.currentTime);gain.gain.exponentialRampToValueAtTime(.001,a.currentTime+.13);o.connect(gain);gain.connect(a.destination);o.start();o.stop(a.currentTime+.14);}catch{}},[sound]);
 const reset=(mode:Mode=game.mode,newSeed=false)=>{generation.current++;abort.current?.abort();inflight.current=false;setBusy(false);setRunning(false);setReplay(null);setError('');setHistory([]);setSelected(null);const g=createGame(mode,newSeed?game.seed+1:game.seed);state.current=g;setGame(g);};
 const step=useCallback(async()=>{
  if(inflight.current||state.current.phase==='escaped'||state.current.phase==='stalled')return;
  inflight.current=true;const gen=generation.current,g=state.current,id=activeAgent(g);let next:Game;
  try{
   if(backend==='ollama'){
    if(g.calls>=40||g.tokens>=23000){setRunning(false);setError('Local-model budget reached. Export this run or reset to begin another.');return;}
    if(!model){setRunning(false);setError('Choose an installed model in Mission settings first.');return;}
    setBusy(true);abort.current=new AbortController();const res=await fetch('/api/agent',{method:'POST',headers:{'Content-Type':'application/json'},signal:abort.current.signal,body:JSON.stringify({model,packet:agentPacket(g,id)})});const data=await res.json() as {action:Action;inputTokens:number;outputTokens:number;error?:string};if(!res.ok)throw new Error(data.error||'Local model request failed.');
    next=applyAction(g,id,data.action as Action);next.calls++;next.inputTokens+=data.inputTokens||0;next.outputTokens+=data.outputTokens||0;next.tokens=next.inputTokens+next.outputTokens;
   }else next=applyAction(g,id,policy(g,id));
   if(gen!==generation.current)return;setMission(next);if(next.events.length>g.events.length)beep();if(next.phase==='escaped'||next.phase==='stalled')setRunning(false);
  }catch(e){if(gen===generation.current&&(e as Error).name!=='AbortError'){setRunning(false);setError((e as Error).message);}}
  finally{if(gen===generation.current){inflight.current=false;setBusy(false);}}
 },[backend,model,beep]);
 useEffect(()=>{if(!running)return;const timer=setTimeout(()=>void step(),backend==='ollama'?200:1900/speed);return()=>clearTimeout(timer);},[running,game,speed,backend,step]);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('echo-station-preferences')||'{}');if(saved.backend==='ollama'&&typeof saved.model==='string'&&saved.model){setBackend('ollama');setModel(saved.model);setModels([saved.model]);}}catch{}setPreferencesReady(true);},[]);
 useEffect(()=>{if(preferencesReady)try{localStorage.setItem('echo-station-preferences',JSON.stringify({backend,model}));}catch{}},[backend,model,preferencesReady]);
 useEffect(()=>()=>{abort.current?.abort();audio.current?.close();},[]);
 useEffect(()=>{log.current?.scrollTo({top:log.current.scrollHeight,behavior:'smooth'});},[view.events.length,tab]);
 useEffect(()=>{if(focusEvidence&&tab==='evidence')document.getElementById('evidence-'+focusEvidence)?.scrollIntoView({behavior:'smooth',block:'nearest'});},[focusEvidence,tab]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.code==='Space'&&!modal&&!['INPUT','BUTTON','TEXTAREA'].includes((e.target as HTMLElement).tagName)){e.preventDefault();if(state.current.phase!=='escaped'&&state.current.phase!=='stalled')setRunning(x=>!x);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[modal]);
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>}}).modelContext;if(!ctx)return;const life=new AbortController();Promise.resolve(ctx.registerTool({name:'read_escape_mission',description:'Read the current station mission progress and measured token usage.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:Record<string,unknown>)=>{if(!input||Object.keys(input).length)throw new Error('Expected an empty object.');const g=state.current;return {phase:g.phase,mode:g.mode,tick:g.tick,power:g.power,authorized:g.decoded,relays:g.holds,tokens:g.tokens};}},{signal:life.signal})).catch(()=>{});return()=>life.abort();},[]);
 const discover=[...new Set(Object.values(view.known).flat())],messages=view.events.filter(e=>e.type==='message').length;
 const done=Number(view.power)+Number(view.decoded)+Number(view.phase==='escaped');
 const selectedAgent=AGENTS.find(a=>a.id===selected);
 const compare=()=>{const rs=(['single','independent','team'] as Mode[]).map(m=>{let g=createGame(m,game.seed);for(let i=0;i<100&&g.phase!=='escaped'&&g.phase!=='stalled';i++){const id=activeAgent(g);g=applyAction(g,id,policy(g,id));}return g;});setResults(rs);setModal('compare');};
 const connect=async()=>{setChecking(true);setError('');try{const r=await fetch('/api/agent');const data=await r.json() as {models:string[];error?:string};if(!r.ok)throw new Error(data.error);setModels(data.models);if(data.models.length){setModel(data.models.includes('qwen3:4b')?'qwen3:4b':data.models[0]);setBackend('ollama');}else setError('Ollama is running, but no models are installed. Pull a tool-capable model, then check again.');}catch(e){setError((e as Error).message);}finally{setChecking(false);}};
 const download=()=>{const blob=new Blob([JSON.stringify({title:'ECHO Station',version:1,backend,model:backend==='ollama'?model:null,game,history},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`echo-station-run-${game.seed}.json`;a.click();URL.revokeObjectURL(url);};
 return <main className="app-shell">
  <header className="topbar"><a className="brand" href="/" aria-label="ECHO Station home"><div className="brand-icon"><Orbit size={24}/></div><span>ECHO<span className="brand-sub">STATION</span></span></a><nav aria-label="Main navigation"><span className="nav-current">Mission control</span><button onClick={()=>{setTab('evidence');}}>Evidence <span className="count">{discover.length}</span></button><button onClick={compare}>Experiments <ArrowUpRight size={13}/></button></nav><div className="header-right"><span className="local-badge"><span/>{backend==='simulation'?'LOCAL SIMULATION':'LOCAL MODEL'}</span><button className="icon-button" onClick={()=>setModal('about')} aria-label="How to play"><Info size={18}/></button><button className="icon-button" onClick={()=>{setRunning(false);setModal('settings');}} aria-label="Mission settings"><Settings2 size={18}/></button></div></header>
  <section className="mission-heading"><div><div className="eyebrow"><span className="tiny-line"/> COOPERATIVE ESCAPE PROTOCOL <span className="muted">/ 001</span></div><h1>The last signal<span>.</span></h1><p>Four agents. Scattered evidence. One way out.</p></div><div className="heading-actions"><div className="scenario"><span>SCENARIO</span><strong>Research station 07</strong><small>Seed {String(game.seed).padStart(3,'0')} · 3 linked puzzles</small></div><button className="button subtle" onClick={()=>reset(game.mode,true)} disabled={busy}><RotateCcw size={15}/> New mission</button></div></section>
  <div className="workspace">
   <aside className="mission-panel"><div className="panel-label"><ScanLine size={15}/> MISSION BRIEF <span>01</span></div><h2>Get everyone out.</h2><p className="brief">The station is sealed. Every agent holds a piece of the solution. Let them find it together.</p><div className="objectives-heading"><span>OBJECTIVES</span><span>{done} / 3</span></div><div className="objectives">{[{title:'Restore main power',detail:view.power?'Station systems online':'Combine wiring + thermal evidence',icon:Zap,done:view.power},{title:'Recover the access code',detail:view.decoded?'Current record verified':'Resolve conflicting access records',icon:LockKeyhole,done:view.decoded},{title:'Coordinate the escape',detail:view.phase==='escaped'?'All four agents evacuated':'Latch both relays. Open the exit.',icon:DoorOpen,done:view.phase==='escaped'}].map((o,i)=><div className={'objective '+(o.done?'complete':'')} key={o.title}><div className="objective-icon">{o.done?<Check size={17}/>:<o.icon size={17}/>}</div><div><span className="objective-number">0{i+1}</span><h3>{o.title}</h3><p>{o.detail}</p></div></div>)}</div>
    <div className="mode-block"><label id="mode-label">AGENT COORDINATION</label><Select value={game.mode} onValueChange={v=>reset(v as Mode)} disabled={busy}><SelectTrigger aria-labelledby="mode-label" className="mode-select"><Network size={15}/><SelectValue/></SelectTrigger><SelectContent>{Object.entries(modes).map(([v,n])=><SelectItem key={v} value={v}>{n}</SelectItem>)}</SelectContent></Select><p>{game.mode==='team'?'Separate minds. Shared discoveries.':game.mode==='single'?'One controller. All discovered evidence.':'Separate minds. Communication disabled.'}</p></div>
    <button className="fault-button" onClick={()=>{setReplay(null);setMission(disrupt(game));}} disabled={game.disrupted||game.phase==='escaped'||game.phase==='stalled'||busy||!game.tick}><Unplug size={16}/><span>{game.disrupted?'Relay fault injected':'Introduce a disruption'}<small>{game.disrupted?'Watch the team recover':'Fail a relay. Test their adaptability.'}</small></span><ChevronRight size={14}/></button>
    <div className="budget"><div><span>INFERENCE BUDGET</span><strong>{backend==='simulation'?'0 tokens':game.tokens.toLocaleString()+' tokens'}</strong></div><div className="budget-track"><span style={{width:backend==='simulation'?'0%':`${Math.min(100,game.tokens/240)}%`}}/></div><p>{backend==='simulation'?'Rule-based agents · no model calls':`${game.calls} / 40 calls · ~24k token ceiling`}</p></div>
   </aside>
   <section className="stage" aria-label="Station and mission controls"><div className="stage-top"><span><span className={'status-dot '+(running?'live':'')}/>{replay!==null?'MISSION REPLAY':game.phase==='escaped'?'MISSION COMPLETE':running?'MISSION IN PROGRESS':'STATION OVERVIEW'}</span><span className="stage-code">ECHO / SECTOR 07</span></div><Station game={view} selected={selected} onSelect={id=>setSelected(x=>x===id?null:id)} resetView={resetView} links={links}/>
    <div className="stage-corner"><span className="coordinate">28° 14′ N &nbsp; 082° 06′ E</span><span className="power-state">{view.outage?<TriangleAlert size={13}/>:<Zap size={13}/>} {view.outage?'RELAY FAILURE':view.power?'POWER ONLINE':'AUXILIARY POWER'}</span></div><div className="view-controls"><button aria-label="Toggle communication links" aria-pressed={links} className={'icon-button '+(links?'active':'')} onClick={()=>setLinks(x=>!x)}><Network size={17}/></button><button className="icon-button" aria-label="Reset camera" onClick={()=>setResetView(x=>x+1)}><Maximize size={17}/></button><button className="icon-button" aria-label={sound?'Mute mission audio':'Enable mission audio'} onClick={()=>setSound(x=>!x)}>{sound?<Volume2 size={17}/>:<VolumeX size={17}/>}</button></div>
    {selectedAgent&&<div className="agent-overlay" style={{borderColor:selectedAgent.color+'66'}}><span style={{color:selectedAgent.color}}>{selectedAgent.name} / {selectedAgent.role}</span><button aria-label="Close agent details" onClick={()=>setSelected(null)}>×</button><p>{view.statuses[selectedAgent.id]}</p><small>{knowledge(view,selectedAgent.id).length} clues known · {selectedAgent.room}</small></div>}
    {game.phase==='ready'&&<div className="start-hint"><span className="hint-icon"><Orbit size={17}/></span><div><strong>Your team is ready.</strong><span>Start the mission to watch cooperation unfold.</span></div></div>}
    {game.phase==='escaped'&&replay===null&&<div className="result-card"><div className="result-icon"><DoorOpen size={26}/></div><span className="eyebrow">ESCAPE CONFIRMED</span><h2>{game.mode==='team'?'Better, together.':'The way is clear.'}</h2><p>All four agents evacuated in {game.tick} turns.<br/>{messages} evidence handoffs. {game.failures} rejected actions.</p><button className="button primary" onClick={()=>{setReplay(0);setRunning(false);}}>Review the mission <ArrowRight size={16}/></button></div>}
    {game.phase==='stalled'&&replay===null&&<div className="result-card"><TriangleAlert className="warning"/><h2>Missing a connection.</h2><p>The agents stopped making progress. Inspect their evidence or try another coordination mode.</p><button className="button primary" onClick={()=>reset('team')}>Try a coordinated team</button></div>}
    <div className="stage-bottom"><span>DRAG TO ORBIT <i/> SCROLL TO ZOOM</span><span><span className="square-dot"/> LIVE 3D ENVIRONMENT</span></div>
   </section>
   <aside className="activity-panel"><div className="panel-label"><Radio size={15}/> TEAM ACTIVITY <span className="activity-count">{view.events.length}</span></div><Tabs value={tab} onValueChange={setTab} className="activity-tabs"><TabsList className="activity-tab-list"><TabsTrigger value="comms">Comms <span>{messages}</span></TabsTrigger><TabsTrigger value="evidence">Evidence <span>{discover.length}</span></TabsTrigger></TabsList><TabsContent value="comms" className="activity-content"><div className="activity-scroll" ref={log}>{view.events.length===0?<div className="empty-comms"><div className="radio-orbit"><Radio size={27}/></div><h3>A quiet channel.<br/>For now.</h3><p>Discoveries, evidence handoffs, and coordinated actions appear here as your team explores.</p><span>CHANNEL 01 · TEAM FREQUENCY</span></div>:view.events.map(e=>{const agent=AGENTS.find(a=>a.id===e.agent);return <article className={'event event-'+e.type} key={e.id}><div className="event-avatar" style={{color:agent?.color||'#a6bdce',borderColor:(agent?.color||'#a6bdce')+'40'}}>{agent?agent.symbol:<Zap size={12}/>}</div><div className="event-body"><div className="event-meta"><strong style={{color:agent?.color}}>{agent?.name||'Station'}</strong><span>{e.type==='message'?'→ '+(e.recipient==='team'?'Team':e.recipient):e.type==='discovery'?'DISCOVERY':e.type.toUpperCase()}</span><time>T{pad(e.tick)}</time></div><p>{e.text}</p>{e.evidence.length>0&&<div className="evidence-links">{e.evidence.map(id=><button key={id} onClick={()=>{setTab('evidence');setFocusEvidence(id);}}><Layers size={10}/>{id}</button>)}</div>}</div></article>})}</div></TabsContent><TabsContent value="evidence" className="activity-content"><div className="activity-scroll evidence-list">{!discover.length&&<div className="empty-comms"><Layers size={28}/><h3>The answers are<br/>in the station.</h3><p>Start the mission. Inspected evidence will be collected here.</p></div>}{evidenceFor(view.seed).filter(e=>discover.includes(e.id)).map(e=>{const a=AGENTS.find(a=>a.id===e.owner)!;return <article id={'evidence-'+e.id} key={e.id} className={'evidence-card '+(focusEvidence===e.id?'focused':'')}><div><span style={{color:a.color}}>{e.id} / {e.kind}</span><Layers size={13}/></div><h3>{e.title}</h3><p>{e.text}</p><small>Found by {a.name} · known to {AGENTS.filter(a=>knowledge(view,a.id).includes(e.id)).length}/4 agents</small></article>})}</div></TabsContent></Tabs><div className="channel-status"><span className="status-dot"/>{busy?'Local model is deciding…':game.mode==='independent'?'Communication disabled':'Evidence attached to messages'}<span>{busy?<LoaderCircle size={13} className="spin"/>:<LockKeyhole size={12}/>}</span></div></aside>
  </div>
  <section className="agents-strip" aria-label="Agent team">{AGENTS.map((a,i)=><button key={a.id} className={'agent-card '+(selected===a.id?'selected':'')} style={{'--agent-color':a.color} as React.CSSProperties} onClick={()=>setSelected(x=>x===a.id?null:a.id)} aria-pressed={selected===a.id}><div className="agent-monogram"><span>{a.symbol}</span><i/></div><div className="agent-card-main"><div><h3>{a.name}</h3><span>{a.role}</span></div><p>{view.phase==='ready'?a.room:view.phase==='escaped'?'Safely evacuated':view.statuses[a.id]}</p></div><div className="agent-card-end"><span className={'agent-state '+(running&&game.turn%4===i?'thinking':'')}>{view.phase==='escaped'?'CLEAR':running&&game.turn%4===i?'ACTIVE':'READY'}</span><small><Layers size={11}/>{knowledge(view,a.id).length}</small></div></button>)}</section>
  <footer className="transport"><div className="transport-main"><button className="button primary run-button" onClick={()=>{setReplay(null);setRunning(x=>!x);}} disabled={game.phase==='escaped'||game.phase==='stalled'}>{running?<Pause size={16}/>:<Play size={16} fill="currentColor"/>}{running?'Pause mission':game.phase==='ready'?'Start mission':'Resume mission'}<kbd>␣</kbd></button><button className="icon-button" aria-label="Advance one turn" disabled={running||busy||game.phase==='escaped'||game.phase==='stalled'} onClick={()=>{setReplay(null);void step();}}><SkipForward size={18}/></button><button className="icon-button" aria-label="Restart current mission" onClick={()=>reset()}><RotateCcw size={16}/></button><button className="speed-button" onClick={()=>setSpeed(x=>x===1?2:x===2?4:1)}>{speed}× <span>speed</span></button></div><div className="transport-stats"><div><span>TURN</span><strong>{pad(view.tick)}<small>/100</small></strong></div><div><span>DISCOVERED</span><strong>{discover.length}<small>/{game.disrupted?9:8}</small></strong></div><div><span>HANDOFFS</span><strong>{pad(messages)}</strong></div></div><div className="transport-right"><button className="text-button" disabled={!history.length} onClick={()=>{setRunning(false);setReplay(replay===null?0:null);}}><RotateCcw size={14}/>{replay===null?'Replay':'Back to live'}</button><button className="icon-button" aria-label="Export mission log" disabled={!history.length} onClick={download}><Download size={16}/></button></div></footer>
  {replay!==null&&<div className="replay-bar"><span>REPLAY · {replay+1}/{history.length}</span><Slider aria-label="Replay position" min={0} max={Math.max(1,history.length-1)} value={[replay]} onValueChange={v=>setReplay(v[0])}/><button onClick={()=>setReplay(null)}>Exit replay</button></div>}
  {error&&!modal&&<div className="error-banner" role="alert"><TriangleAlert size={18}/><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}>×</button></div>}
  <div className="app-footnote"><span>ECHO STATION <i/> AN EXPERIMENT IN COLLECTIVE INTELLIGENCE</span><span>{backend==='simulation'?'Deterministic simulation · zero inference tokens':'Ollama · local inference · no API key'}</span></div>
  <Dialog open={modal!==null} onOpenChange={open=>{if(!open)setModal(null);}}><DialogContent className="mission-dialog"><DialogTitle>{modal==='settings'?'Mission settings':modal==='compare'?'Same station. Different coordination.':'Welcome to ECHO Station.'}</DialogTitle><DialogDescription>{modal==='settings'?'Choose how your agents make decisions.':modal==='compare'?'A reproducible comparison using rule-based policies, identical puzzles, and a 100-turn limit.':'A cooperative escape room where the missing piece is often another agent’s discovery.'}</DialogDescription>
   {modal==='about'&&<div className="about-content"><p>Start the mission and watch four specialists inspect their rooms. Select an agent to see its status, or open Evidence to inspect what the team has learned.</p><ol><li><Zap size={17}/><span><strong>Combine clues</strong>Wiring, symbols, and thermal timing must agree before power can be restored.</span></li><li><LockKeyhole size={17}/><span><strong>Resolve a contradiction</strong>The archive is out of date. Find the latest authorization record.</span></li><li><Network size={17}/><span><strong>Coordinate a handoff</strong>Two agents latch relays so a third can open the exit.</span></li></ol><p className="note">Simulation mode uses deterministic rules and authored message templates. Local-model mode uses real Ollama decisions. Neither mode requires an API key.</p><button className="button primary" onClick={()=>setModal(null)}>Enter mission control <ArrowRight size={15}/></button></div>}
   {modal==='settings'&&<div className="settings-content">{error&&<div className="error-banner" role="alert"><TriangleAlert size={18}/><span>{error}</span></div>}<label>DECISION ENGINE</label><Select value={backend} onValueChange={v=>{reset();setBackend(v);}}><SelectTrigger className="wide-select" aria-label="Decision engine"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="simulation">Simulation · zero tokens</SelectItem><SelectItem value="ollama">Ollama · local AI agents</SelectItem></SelectContent></Select><p>{backend==='simulation'?'A deterministic, evidence-driven demonstration. Messages are templates; actions are validated by the game engine.':'Run this source on your computer with Ollama running. The hosted version cannot access a model on your computer.'}</p><button className="button subtle" onClick={connect} disabled={checking||game.tick>0}>{checking?<LoaderCircle size={15} className="spin"/>:<Radio size={15}/>} Detect local models</button>{game.tick>0&&<small>Restart the mission before connecting a model.</small>}{models.length>0&&<Select value={model} onValueChange={setModel}><SelectTrigger className="wide-select" aria-label="Local model"><SelectValue/></SelectTrigger><SelectContent>{models.map(m=><SelectItem value={m} key={m}>{m}</SelectItem>)}</SelectContent></Select>}<div className="settings-budget"><span>Model call limit <strong>40 calls</strong></span><span>Token stop threshold <strong>23,000 tokens</strong></span><span>Per-call output limit <strong>220 tokens</strong></span></div><p className="note">Only observations and recent events are sent. Token counts come from Ollama. One final request may cross the stop threshold. No silent fallback to simulation.</p></div>}
   {modal==='compare'&&<div className="comparison-content"><div className="comparison-table"><div className="table-row table-header"><span>Mode</span><span>Result</span><span>Turns</span></div>{results.map(r=><div className="table-row" key={r.mode}><strong>{modes[r.mode]}</strong><span className={r.phase==='escaped'?'success-text':'warning'}>{r.phase==='escaped'?'Escaped':'Stalled'}</span><span>{r.tick}</span></div>)}</div><p>All modes control the same four characters. The single controller sees all discovered evidence. Independent agents keep discoveries private; the coordinated team shares them.</p><p className="note">This tests communication mechanics, not LLM superiority. A central controller can be faster on this small puzzle. Export actual local-model runs to compare measured tokens and outcomes.</p><button className="button primary" onClick={()=>{setModal(null);reset('team');}}>Run coordinated mission <Play size={14}/></button></div>}
  </DialogContent></Dialog>
 </main>;
}
